# Defaults
NAMESPACE: sso-test
OCP_APPS_DOMAIN: "{{ VAULT_OCP_APPS_DOMAIN }}"

# POSTGRES params
POSTGRES_USER: guac
POSTGRES_PASSWORD: "{{ VAULT_POSTGRES_PASSWORD }}"
POSTGRES_DATABASE: guacamole_db

# description: Guacadmin Password
GUACADMIN_PASSWORD: "{{ VAULT_GUACADMIN_PASSWORD }}"

# description: Log Level
LOG_LEVEL: INFO

KEYCLOAK_PASSWORD: "{{ VAULT_KEYCLOAK_PASSWORD }}"
KEYCLOAK_USER: admin
KEYCLOAK_DB_VENDOR: h2
SSO_CLINET_SECRET: "{{ VAULT_SSO_CLINET_SECRET }}"
SSO_CLIENT_ID: daac

# Deployment Version
VERSION: dev

#### User to create in KeyCloak

user:
  username: "{{  vault_user.username }}"
  firstName: "{{  vault_user.firstName }}"
  lastName: "{{  vault_user.lastName }}"
  email: "{{  vault_user.email }}"
  password: "{{  vault_user.password }}"