kind: ConfigMap
apiVersion: v1
metadata:
  namespace: "{{ NAMESPACE }}"
  name: guac-configmap
  labels:
    app.kubernetes.io/name: guac
    app.kubernetes.io/part-of: dcaas  
    app.kubernetes.io/component: server
    app.openshift.io/runtime: java  
data:
  guacamole.properties: |-
    # Guac
    guacd-hostname: guacd
    guacd-port: 4822
    # Auth
    http-auth-header: X-Auth-Username
    # Postgres
    postgresql-hostname: postgres
    postgresql-port: 5432
    postgresql-database: {{ POSTGRES_DATABASE }}
    postgresql-username: {{ POSTGRES_USER }}
    postgresql-password: {{ POSTGRES_PASSWORD }}