apiVersion: v1
kind: DeploymentConfig
metadata:
  namespace: "{{ NAMESPACE }}"
  annotations:
    description: Guacamole Daemon
  name: guacd
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: integration
    app.openshift.io/runtime: java    
spec:
  replicas: 1
  selector:
    name: guacd
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: guacd
      name: guacd
    spec:
      containers:
      - name: guacd
        image: "guacd:{{ VERSION }}"
        imagePullPolicy: Always    
        ports:
        - name: guacd-port
          containerPort: 4822
        readinessProbe:
          tcpSocket:
            port: guacd-port
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: guacd-port
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: HOME
          value: /home/user
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - guacd
      from:
        kind: ImageStreamTag
        name: "guacd:{{ VERSION }}"
    type: ImageChange
