apiVersion: "v1"
kind: "ImageStream"
metadata:
  namespace: "{{ NAMESPACE }}"
  name: "daac-api"
  labels:
    app.kubernetes.io/name: daac-api
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: frontend
    app.openshift.io/runtime: python  
spec:
  dockerImageRepository: quay.io/rarm_sa/daac-api