apiVersion: "v1"
kind: "ImageStream"
metadata:
  namespace: "{{ NAMESPACE }}"
  name: "guacd"
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: integration
    app.openshift.io/runtime: java  
spec:
  dockerImageRepository: quay.io/rarm_sa/guacd
