apiVersion: "v1"
kind: "ImageStream"
metadata:
  namespace: "{{ NAMESPACE }}"
  name: "gdesk"
  labels:
    app.kubernetes.io/name: gdesk
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: desktop   
spec:
  dockerImageRepository: quay.io/rarm_sa/gdesk