apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ NAMESPACE }}"
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: postgres
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: database   
stringData:
  database-name: "{{ POSTGRES_DATABASE }}"
  database-password: "{{ POSTGRES_PASSWORD }}"
  database-user: "{{ POSTGRES_USER }}"
