apiVersion: v1
kind: Service
metadata:
  namespace: "{{ NAMESPACE }}"
  name: daac-api
  labels:
    app.kubernetes.io/name: daac-api
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: frontend
    app.openshift.io/runtime: python
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: daac-api      