apiVersion: v1
kind: Service
metadata:
  namespace: "{{ NAMESPACE }}"
  name: postgres
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: database
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres
    