kind: ConfigMap
apiVersion: v1
metadata:
  namespace: "{{ NAMESPACE }}"
  name: configmap-sso
  labels:
    app.kubernetes.io/name: sso
    app.kubernetes.io/part-of: dcaas  
    app.kubernetes.io/component: server
    app.openshift.io/runtime: java  
data:
  KEYCLOAK_USER: "{{ KEYCLOAK_USER }}"
  KEYCLOAK_PASSWORD: "{{ KEYCLOAK_PASSWORD }}"
  DB_VENDOR: "{{ KEYCLOAK_DB_VENDOR }}"
  PROXY_ADDRESS_FORWARDING: 'true'