apiVersion: "v1"
kind: "ImageStream"
metadata:
  namespace: "{{ NAMESPACE }}"
  name: "sso"
  labels:
    app.kubernetes.io/name: sso
    app.kubernetes.io/part-of: dcaas  
    app.kubernetes.io/component: server
    app.openshift.io/runtime: java  
spec:
  dockerImageRepository: quay.io/keycloak/keycloak
