kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: "{{ NAMESPACE }}"
  name: keycloak-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem