apiVersion: v1
kind: Service
metadata:
  namespace: "{{ NAMESPACE }}"
  name: sso
  labels:
    app.kubernetes.io/name: sso
    app.kubernetes.io/part-of: dcaas  
    app.kubernetes.io/component: server  
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: sso